version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eventcad-postgres-dev
    environment:
      POSTGRES_DB: eventcad_dev
      POSTGRES_USER: eventcad_user
      POSTGRES_PASSWORD: eventcad_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - eventcad-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventcad_user -d eventcad_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  eventcad-network:
    driver: bridge 